#define TECHNIQUE_FAIL        0
#define TECHNIQUE_MISSED      1
#define TECHNIQUE_SUCCESS     2
#define TECHNIQUE_EFFECTIVE   4
#define TECHNIQUE_INEFFECTIVE 8
#define TECHNIQUE_CRITICAL    16

#define BATTLE_STARTING 0
#define BATTLE_IN_PROGRESS 1
#define BATTLE_TURN_PROGRESSING 2
#define BATTLE_ENDING 3
#define BATTLE_ENDED 4