#define MD_MHP   "maxhealth"
#define MD_CHP   "currenthealth"
#define MD_ATK   "attack"
#define MD_DEF   "defence"
#define MD_SPATK "specialattack"
#define MD_SPDEF "specialdefence"
#define MD_SPEED "speed"
#define MD_LVL   "level"
#define MD_EXP   "experience"
#define MD_FLEE  "fleechance"

#define DAM_NEUTRAL "neutral"