#define TRAINER_ICON_BODY    "body"
#define TRAINER_ICON_EYES    "eyes"
#define TRAINER_ICON_HAIR    "hair"
#define TRAINER_ICON_BEARD   "beard"
#define TRAINER_ICON_CLOTHES "clothes"
#define TRAINER_ICON_HAT     "hat"

#define ALL_TRAINER_ICON_STRINGS list(TRAINER_ICON_BODY, TRAINER_ICON_EYES, TRAINER_ICON_HAIR, TRAINER_ICON_BEARD, TRAINER_ICON_CLOTHES, TRAINER_ICON_HAT)